name: codenic_logger
description: A detailed logger with support for Firebase Crashlytics.
version: 0.1.0
homepage: https://github.com/CodenicCoders/codenic_logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logger: ^1.1.0
  meta: ^1.7.0

dev_dependencies:
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0
  test: ^1.19.4
