name: codenic_logger
description: An enhanced logger for providing structured and detailed log messages.
version: 0.3.0
repository: https://github.com/CodenicCoders/codenic_logger
issue_tracker: https://github.com/CodenicCoders/codenic_logger/issues
homepage: https://github.com/CodenicCoders/codenic_logger
documentation: https://github.com/CodenicCoders/codenic_logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logger: ^1.1.0
  meta: ^1.7.0

dev_dependencies:
  mocktail: ^0.2.0
  test: ^1.19.5
  very_good_analysis:
