name: codenic_logger
description: A logger extension for providing structured and mutable log messages.
version: 1.0.0
repository: https://github.com/CodenicCoders/codenic_logger
issue_tracker: https://github.com/CodenicCoders/codenic_logger/issues
homepage: https://github.com/CodenicCoders/codenic_logger
documentation: https://github.com/CodenicCoders/codenic_logger

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  logger: ^1.1.0
  meta: ^1.8.0

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.22.0
  very_good_analysis: ^3.1.0
