name: codenic_logger
description: A Flutter package used for printing detailed message logs with
  informational data.
version: 0.1.0
homepage: null

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  firebase_crashlytics: ^2.3.0
  flutter:
    sdk: flutter
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  mocktail: ^0.2.0
