name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get
      
      - name: Format
        run: dart format --set-exit-if-changed .
        
      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .
        
      - name: Run Tests
        run: dart run test

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          
      - name: Verify Pub Score
        run: pana .
