name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get
      
      - name: Format
        run: flutter format --set-exit-if-changed .
        
      - name: Analyze
        run: flutter analyze
        
      - name: Run Tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          
      - name: Verify Pub Score
        run: pana .
