name: main

on:
  push:
    branches: [ master ]
    
  pull_request:
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: flutter pub get
      
      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Run Tests
        run: |
          pub global activate test_coverage
          export PATH=$PATH:$HOME/.pub-cache/bin
          test_coverage
              
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1

      - name: Install Dependencies
        run: |
          flutter packages get
          flutter pub global activate pana
          
      - name: Verify Pub Score
        run: pana .
